### ISSUE TITLE
Dataset missing for the disease.

### ISSUE THREAD

**Issue by rishiagrawal2609** [rsharvesh16/Predict-IT-CropPrediction#1]
Please provide the dataset for the training the model. there is a DB file but there is no description for the same, how to unpack it.

**Comment by rishiagrawal2609** [comment]
Copy of https://jovian.ml/soumyajit4419/course-project-plant-disease-classification - Direct Upload. No changes.

**Comment by rsharvesh16** [comment]
Hi @rishiagrawal2609, Thanks for going through the project, This project was made for learning purpose and wanted to add some more features in it. Yes, its a copy but implemented some features of ours as well for a better learning. Thanks.
